name: newsfeed_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  equatable: ^2.0.7
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  fpdart: ^1.1.1
  go_router: ^15.1.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  riverpod_annotation: ^2.6.1
  string_validator: ^1.1.0
  supabase_flutter: ^2.9.0
  uuid: ^4.5.1
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true

  assets:
    - .env
